browser=edge

baseUrl=https://demoqa.com
implicitWait=10
explicitWait=10

# Execution Mode Options: true (run without UI), false (run with UI browser visible)
headless=true

# Execution Target Options: local (run on your machine), grid (run on a remote Selenium Grid hub server)
executionEnv=local

# URL address pointing directly to your active remote Selenium Grid Router/Hub endpoint
gridUrl=http://localhost:4444/wd/hub