name: Customised JAR FW Test Automation Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  automation-execution:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Framework Code
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Pre-load Maven Dependency Cache
        run: mvn dependency:go-offline

      - name: Execute Automation Test Suite (Headless Mode)
        run: |
          mvn clean test -Dbrowser=chrome -Dheadless=true

      - name: Archive HTML Extent Execution Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-automation-reports
          path: |
            reports/
            test-output/
          retention-days: 5

      - name: Archive Failure Defect Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: regression-failure-screenshots
          path: screenshots/
          retention-days: 5